apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::962544650039:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-A3I8CCRU482F
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::962544650039:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-07T23:12:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1596"
  uid: deb6670d-c717-4929-bcf9-0a235ba74cb4